/* ---------- v67 THE ART VARIANTS: the registry, the loader and the shuffle bags (T82ART) ----------
   The owner (2026-09-30): the reel's giant L "gets pretty stale seeing the same L over again"; he wants "a ton of
   different variations", ten in a row all different, and the same for the reel's win and loss dots and the results
   mountain. One limit: nothing on the player's side may get slower, even on an iPhone SE. art/CONTRACT.md is the
   whole contract; this file is its T82ART.

   Each variant is its own small file (art/<kind>/<id>.js) that registers itself here with add(). art-index.js
   (generated by node tools/art-index.js) lists every file with its cache key, so the phone knows the whole library
   without downloading any of it. When a draft starts, app.js asks this device's shuffle bag for the next ones
   (deal), loads just those in the background (load), and the reel and the results print use them; only a look that
   actually plays leaves the bag (used). A bag deals every variant once before any repeats, so ten losses in a row
   are ten different looks, and a season downloads the same handful of files whether the library holds 30 or 1,000.
   The built-in looks (the classic L and dots in reel-riso.js, the lake in results-riso.js) register themselves with
   builtin: true and ride in the bags like any variant.

   Part two (art/CONTRACT-FX.md): the owner's Heat Check, Presti perk and 82-0 firework effects come in many looks too,
   so three more kinds ride the same registry, loader and bags: hot, perk and goat (riso-fx.js plays them). And an
   82-0 season gets its own pictures: a scene with perfect: true is dealt only from the perfect bag (deal("scene", 1,
   { perfect: true })), never for anything less, and an ordinary deal never hands one out, so 82-0 prints like
   nothing an 81-1 can earn.

   Nothing here runs on its own: no download before a draft starts, no timers, and no document access until load()
   is called. Every storage call is wrapped (in private mode the bags live in memory for the visit). ES5, like the
   engines; test.js runs the bag logic in node, where there is no window or document.

   The owner's picks (2026-10-02): "handle preloading smartly to not drag performance for users with slower phones
   and/or slow internet", and on Data Saver or a 2G/3G connection "skip downloading new looks and play the built-ins".
   So deal() hands out nothing on a slow link (lean(): navigator.connection says saveData, or an effectiveType of
   slow-2g, 2g or 3g): every moment plays its built-in, nothing downloads and the bags stay put. Safari has no
   navigator.connection, so an iPhone always takes the normal path (app.js loads that in stages). And his speed dial
   (art/tempo.json, which tools/art-index.js writes into each look's entry) rides the index: tempo(kind, id). */
var T82ART = (typeof T82ART !== "undefined" && T82ART && T82ART.add) ? T82ART : (function () {
  "use strict";
  var KINDS = ["loss", "dots", "scene", "hot", "perk", "goat"];   // part two: the Heat Check, the Presti perks, 82-0
  var ID = /^[a-z0-9-]+$/;                           // a variant's id is its file's name
  var LOAD_MS = 8000;                                // a file that has not arrived by then is skipped (the built-in plays)
  var LIVE_HOST = /^(www\.)?true82\.net$/i;          // app.js's offLiveHost: QA forcing never works on the real site
  var REG = { loss: {}, dots: {}, scene: {}, hot: {}, perk: {}, goat: {} };   // kind -> id -> def (variants and built-ins)
  var INDEX = [], BYKEY = {};                        // art-index.js's entries, and each one by "kind/id"
  var OFFB = {};                                     // "kind/id" -> 1: a built-in art/enabled.json switched off (never dealt)
  var SLOW = /^(?:slow-2g|2g|3g)$/;                  // the connections that get no art downloads (the owner, 2026-10-02)
  var PENDING = {}, WAIT = {}, FAILED = {};          // "kind/id" -> a load in flight, its finisher, a load that failed
  var MEM = {}, SOLO = {};                           // the bags when the device will not keep them (private mode)
  var BASE = null;                                   // where the art files live: beside this file

  function has(o, k) { return Object.prototype.hasOwnProperty.call(o, k); }
  function isArr(a) { return Object.prototype.toString.call(a) === "[object Array]"; }
  function isKind(k) { return KINDS.indexOf(k) >= 0; }
  function isId(id) { return typeof id === "string" && ID.test(id); }
  function nonEmpty(a) { return a.length > 0; }
  function uniq(list) { var out = [], seen = {}; list.forEach(function (x) { if (!has(seen, x)) { seen[x] = 1; out.push(x); } }); return out; }
  function setOf(list) { var o = {}; list.forEach(function (x) { o[x] = 1; }); return o; }   // membership in O(1): a library of 1,000 stays cheap
  function warn(msg) { try { if (typeof console !== "undefined" && console.warn) console.warn("[t82] art: " + msg); } catch (err) {} }

  /* ---- the registry ---- */
  // A variant file (or an engine's built-in) registers its look. A file that is loading resolves its load() here.
  function add(kind, id, def) {
    if (!isKind(kind) || !isId(id) || !def || typeof def !== "object") { warn("add(" + kind + ", " + id + ") ignored: kind, id or def is not valid"); return false; }
    REG[kind][id] = def;
    if (WAIT[kind + "/" + id]) WAIT[kind + "/" + id]();
    return true;
  }
  function get(kind, id) { return isKind(kind) && typeof id === "string" && has(REG[kind], id) ? REG[kind][id] : null; }
  // art-index.js hands over the library once: { kind, id, name, file: "art/<kind>/<id>.js?v=<key>", on, tempo? }.
  // opts.off: the built-ins art/enabled.json switched off ("perk/classic"): they still stand in for a look that is not
  // there, but a bag never deals them.
  function index(list, opts) {
    INDEX = (isArr(list) ? list : []).filter(function (en) {
      return en && isKind(en.kind) && isId(en.id) && typeof en.file === "string" && !!en.file;
    }).map(function (en) {
      return { kind: en.kind, id: en.id, name: String(en.name || en.id), file: en.file, on: en.on === true, perfect: en.perfect === true, tempo: dial(en.tempo) };
    });
    BYKEY = {};
    INDEX.forEach(function (en) { if (!has(BYKEY, en.kind + "/" + en.id)) BYKEY[en.kind + "/" + en.id] = en; });
    OFFB = {};
    (opts && isArr(opts.off) ? opts.off : []).forEach(function (k) {
      var p = String(k).split("/");
      if (p.length === 2 && isKind(p[0]) && isId(p[1])) OFFB[p[0] + "/" + p[1]] = 1;
    });
    return INDEX.length;
  }
  // the owner's speed dial for one look (art/tempo.json): { from: a phase its def declares, or 0 (the whole moment),
  // x: how many times faster from there, 1 to 3 }; anything else is no dial (the look plays at its own pace)
  function dial(t) {
    if (!t || typeof t !== "object") return null;
    var x = +t.x, from = t.from;
    if (!(x >= 1 && x <= 3) || !(from === 0 || isId(from))) return null;
    return { from: from, x: x };
  }
  function tempo(kind, id) { var en = isKind(kind) && typeof id === "string" ? entry(kind, id) : null, t = en && en.tempo; return t ? { from: t.from, x: t.x } : null; }
  function entry(kind, id) { return has(BYKEY, kind + "/" + id) ? BYKEY[kind + "/" + id] : null; }
  // every index entry of a kind, loaded or not, on or off (the lab shows them all)
  function catalog(kind) {
    return INDEX.filter(function (en) { return en.kind === kind; }).map(function (en) {
      return { kind: en.kind, id: en.id, name: en.name, file: en.file, on: en.on, perfect: en.perfect, tempo: tempo(en.kind, en.id) };
    });
  }
  // part two: an 82-0 look (art-index.js reads perfect: true from the file without running it; a registered def
  // that says so counts too, for a look the lab loads by hand)
  function isPerfect(kind, id) {
    var en = isKind(kind) && typeof id === "string" ? entry(kind, id) : null, def = get(kind, id);
    return !!((en && en.perfect) || (def && def.perfect === true));
  }
  // builtin: true counts only for the engines' own looks (the classic L and dots, the lake; a kind with none reserved
  // here: a def no index entry names). A variant file that copies the flag stays a variant: art/enabled.json still
  // switches it off.
  var BUILTIN = { loss: "classic", dots: "classic", scene: "lake" };
  function isBuiltin(kind, id) {
    var def = get(kind, id);
    return !!def && def.builtin === true && (has(BUILTIN, kind) ? BUILTIN[kind] === id : !entry(kind, id));
  }
  // the ids a bag deals: the index's "on" entries plus the built-ins the engines registered (less any art/enabled.json
  // switched off: the owner cut perk classic on 2026-10-02, and it still stands in for a look not there yet). The
  // perfect looks are a bag of their own: enabled(kind) never lists one, enabled(kind, { perfect: true }) only them.
  function enabled(kind, opts) {
    if (!isKind(kind)) return [];
    var want = !!(opts && opts.perfect), out = [], id;
    INDEX.forEach(function (en) { if (en.kind === kind && en.on) out.push(en.id); });
    for (id in REG[kind]) if (has(REG[kind], id) && isBuiltin(kind, id) && !has(OFFB, kind + "/" + id)) out.push(id);
    return uniq(out).filter(function (x) { return isPerfect(kind, x) === want; });
  }
  // A slow link (the owner, 2026-10-02): Data Saver on, or a connection the browser rates slow-2g, 2g or 3g. Read at
  // each deal, so a phone that turns Data Saver off gets the library on its next draft. Safari has no
  // navigator.connection: false there.
  function lean() {
    try {
      var n = typeof navigator !== "undefined" && navigator ? navigator : null;
      var c = n ? n.connection || n.mozConnection || n.webkitConnection : null;
      return !!c && (c.saveData === true || SLOW.test(String(c.effectiveType || "")));
    } catch (err) { return false; }
  }

  /* ---- the loader ---- */
  // The files sit beside this script (art/ next to art-core.js), so a page in a subfolder (a lab) finds them too.
  function urlOf(file) {
    if (/^(?:[a-z][a-z0-9+.-]*:)?\/\//i.test(file) || file.charAt(0) === "/") return file;
    try {
      if (BASE === null) {
        var me = document.querySelector('script[src*="art-core.js"]');
        BASE = me && me.src ? me.src : "";
      }
      if (BASE && typeof URL === "function") return new URL(file, BASE).href;
    } catch (err) {}
    return file;
  }
  function loadOne(kind, id) {
    var key = kind + "/" + id, en = entry(kind, id);
    if (get(kind, id) || FAILED[key] || !en || typeof document === "undefined" || !document || !document.createElement) return Promise.resolve();
    if (PENDING[key]) return PENDING[key];
    PENDING[key] = new Promise(function (resolve) {
      var done = false, timer = 0, s;
      function finish() {
        if (done) return;
        done = true;
        clearTimeout(timer);
        delete WAIT[key]; delete PENDING[key];
        if (!get(kind, id)) FAILED[key] = 1;   // an error, a timeout or a file that never registered: skip it for this visit
        resolve();
      }
      WAIT[key] = finish;
      try {
        s = document.createElement("script");
        s.async = true;
        s.src = urlOf(en.file);                // the index's file carries its ?v= key: cached a year, fetched once
        s.setAttribute("data-t82-art", key);
        s.onload = finish; s.onerror = finish;
        timer = setTimeout(finish, LOAD_MS);
        (document.head || document.documentElement).appendChild(s);
      } catch (err) { finish(); }
    });
    return PENDING[key];
  }
  // Promise -> the requested ids that are now registered. Never rejects, never loads anything unless asked, and two
  // calls for the same file share one request.
  function load(kind, ids) {
    var list = uniq((isArr(ids) ? ids : [ids]).filter(isId));
    function now() { return isKind(kind) ? list.filter(function (id) { return !!get(kind, id); }) : []; }
    if (!isKind(kind) || !list.length) return Promise.resolve(now());
    return Promise.all(list.map(function (id) { return loadOne(kind, id); })).then(now, now);
  }

  /* ---- the shuffle bags ----
     One bag per kind on this device (localStorage "t82-art-bag-<kind>"; the 82-0 scenes "t82-art-bag-scene-perfect"):
     { k: the ids it was drawn from, b: cycles }.
     Each cycle is one shuffle of every enabled id, so every look plays once before any repeats; the first cycle is the
     one in progress, the rest were drawn ahead so a peek stays stable (what app.js loaded is what plays). A new cycle
     never starts with the look that played last. A dealt look that never arrived moves on as if used (skip), so one
     that cannot load on this device never freezes the bag. A look switched off (or deleted) leaves the bag; a look
     added since the bag was drawn joins the cycle in progress, so a growing library shows up the next season, not
     cycles later. */
  function store() { try { return typeof localStorage !== "undefined" && localStorage ? localStorage : null; } catch (err) { return null; } }
  function readKey(k) {
    if (!SOLO[k]) { try { var s = store(), v = s ? s.getItem(k) : null; if (v != null) return v; } catch (err) {} }
    return has(MEM, k) ? MEM[k] : null;
  }
  // A write the device refuses (private mode, a full disk) keeps the bag in memory, and reads stop trusting the
  // stale stored copy, so the bag still moves for the rest of the visit.
  function writeKey(k, v) {
    MEM[k] = v;
    try { var s = store(); if (!s) throw new Error("no storage"); s.setItem(k, v); SOLO[k] = false; } catch (err) { SOLO[k] = true; }
  }
  function bagKey(kind) { return "t82-art-bag-" + kind; }
  function lastKey(kind) { return "t82-art-last-" + kind; }
  function readBag(kind) {
    var o = null;
    try { o = JSON.parse(readKey(bagKey(kind)) || "null"); } catch (err) { o = null; }
    if (!o || !isArr(o.k) || !isArr(o.b)) return { k: [], b: [] };
    return { k: o.k.filter(isId), b: o.b.filter(isArr).map(function (c) { return c.filter(isId); }).filter(nonEmpty) };
  }
  function writeBag(kind, bag) { writeKey(bagKey(kind), JSON.stringify({ k: bag.k, b: bag.b })); }
  function readLast(kind) { var v = readKey(lastKey(kind)); return isId(v) ? v : null; }
  function rnd(n) { return Math.floor(Math.random() * n); }   // cosmetic: Math.random (a bag is per device, never replayed)
  function shuffled(ids, prev) {
    var a = ids.slice(), i, j, t;
    for (i = a.length - 1; i > 0; i--) { j = rnd(i + 1); t = a[i]; a[i] = a[j]; a[j] = t; }
    if (a.length > 1 && a[0] === prev) { j = 1 + rnd(a.length - 1); t = a[0]; a[0] = a[j]; a[j] = t; }
    return a;
  }
  function tidy(bag, on) {
    var known = setOf(bag.k), live = setOf(on), fresh = on.filter(function (id) { return !has(known, id); });
    bag.b = bag.b.map(function (c) { return c.filter(function (id) { return has(live, id); }); }).filter(nonEmpty);
    if (fresh.length && bag.b.length) {
      // looks new since the bag was drawn join the cycle in progress, and the cycles drawn ahead are redrawn with
      // them (a bag drawn when only the built-in existed would otherwise lead every cycle with it for many seasons)
      bag.b = bag.b.slice(0, 1);
      var c = bag.b[0], inC = setOf(c);
      fresh.forEach(function (id) { if (!has(inC, id)) c.splice(rnd(c.length + 1), 0, id); });
    }
    seams(bag.b);
    bag.k = on.slice();
  }
  // No look twice running where two cycles meet: a cycle that opens with the look the one before it ends on swaps its
  // head away, and a one-look cycle that repeats it merges into it (a bag that piled up a look that never arrived).
  function seams(b) {
    for (var i = 1, p, c, j, t; i < b.length; i++) {
      p = b[i - 1]; c = b[i];
      if (c[0] !== p[p.length - 1]) continue;
      if (c.length === 1) { b.splice(i--, 1); continue; }
      j = 1 + rnd(c.length - 1); t = c[0]; c[0] = c[j]; c[j] = t;
    }
  }
  // part two: the perfect looks keep a bag of their own ("t82-art-bag-scene-perfect"), so an 82-0 never draws an
  // ordinary scene and an ordinary season never draws an 82-0 one; the ordinary bag's key is unchanged
  function bagName(kind, perfect) { return perfect ? kind + "-perfect" : kind; }
  // PEEK the next n ids of this device's bag (refilling as needed). Consumes nothing: two deals in a row agree.
  // opts.perfect: deal from the perfect bag (the 82-0 scenes) instead. On a slow link (lean()) nothing: the built-ins
  // play, nothing downloads, and the bag is not even read.
  function deal(kind, n, opts) {
    n = Math.max(0, Math.floor(+n || 0));
    if (!n || lean()) return [];
    var on = enabled(kind, opts), name = bagName(kind, !!(opts && opts.perfect));
    if (!on.length) return [];
    var bag = readBag(name), flat, c;
    tidy(bag, on);
    flat = [].concat.apply([], bag.b);
    while (flat.length < n) {
      c = shuffled(on, flat.length ? flat[flat.length - 1] : readLast(name));
      bag.b.push(c);
      flat = flat.concat(c);
    }
    writeBag(name, bag);
    return flat.slice(0, n);
  }
  // A look actually played: take it out of the bag (its first place in line) and remember it as the last one. A
  // perfect look leaves the perfect bag on its own (opts.perfect, true or false, names the bag outright).
  function used(kind, id, opts) {
    if (!isKind(kind) || !isId(id)) return;
    var name = bagName(kind, opts && typeof opts.perfect === "boolean" ? opts.perfect : isPerfect(kind, id));
    var bag = readBag(name), i, at;
    for (i = 0; i < bag.b.length; i++) { at = bag.b[i].indexOf(id); if (at >= 0) { bag.b[i].splice(at, 1); break; } }
    bag.b = bag.b.filter(nonEmpty);
    writeBag(name, bag);
    writeKey(lastKey(name), id);
  }
  // A dealt look that did not play because it was not there: its file failed, timed out or never registered on this
  // device (a load-time throw, syntax an old iPhone cannot parse), or the engine had switched it off. It moves on like
  // a used one (it comes back next cycle, and a fresh cycle does not open with it), so a look that cannot load here
  // never sits at the head of the bag and freezes it. A file still loading keeps its place (it plays next time).
  // The reel reports its skips (opts.onSkip), app.js the print's scene. Returns whether the look moved on.
  function skip(kind, id, opts) {
    if (!isKind(kind) || !isId(id) || PENDING[kind + "/" + id]) return false;
    used(kind, id, opts);
    return true;
  }

  /* ---- QA ----
     On a test build (any host but true82.net and www.true82.net), ?art=loss:seal,dots:balls,scene:skyline forces
     those looks; loss:a+b+c plays a, b and c in turn. Returns the ids, or null. The live site ignores it.
     Part two: the FX kinds too (hot:x, perk:y, goat:z), and perfect:w forces the 82-0 scene: forced("perfect"), or
     forced("scene", { perfect: true }); a plain forced("scene") never returns the perfect list. */
  function forced(kind, opts) {
    if (kind === "scene" && opts && opts.perfect) kind = "perfect";
    if (!isKind(kind) && kind !== "perfect") return null;
    try {
      var loc = typeof location !== "undefined" ? location : null;
      if (!loc || LIVE_HOST.test(String(loc.hostname || ""))) return null;
      var m = /[?&]art=([^&#]*)/.exec(String(loc.search || ""));
      if (!m) return null;
      var parts = decodeURIComponent(m[1].replace(/\+/g, " ")).split(","), i, kv, ids;
      for (i = 0; i < parts.length; i++) {
        kv = parts[i].split(":");
        if (kv.length !== 2 || kv[0].replace(/\s+/g, "") !== kind) continue;
        ids = kv[1].split(/[\s+]+/).filter(isId);   // a "+" in a query arrives as a space; an escaped one (%2B) as "+"
        return ids.length ? ids : null;
      }
    } catch (err) {}
    return null;
  }

  return { add: add, get: get, index: index, catalog: catalog, enabled: enabled, load: load, deal: deal, used: used,
    skip: skip, forced: forced, perfect: isPerfect, tempo: tempo, lean: lean, KINDS: KINDS.slice(), LOAD_MS: LOAD_MS, version: "v67" };
})();
if (typeof window !== "undefined" && window) window.T82ART = T82ART;
