/* GENERATED by node tools/art-index.js from art/loss, art/dots and art/scene: never hand-edit (art/CONTRACT.md).
   One entry per variant file; "on" = the game deals it (art/enabled.json lists the ones that are off; the lab shows
   them all). Each file's ?v= key is the cache-key manifest's: node tools/cache-keys.js --stamp <key> rewrites it. */
(function () {
  "use strict";
  if (typeof T82ART === "undefined" || !T82ART || !T82ART.index) return;
  T82ART.index([
    { kind: "loss", id: "seal", name: "Rubber Seal", file: "art/loss/seal.js?v=20260930-v67", on: true },
    { kind: "dots", id: "balls", name: "Ball and Brick", file: "art/dots/balls.js?v=20260930-v67", on: true },
    { kind: "scene", id: "skyline", name: "Skyline", file: "art/scene/skyline.js?v=20260930-v67", on: true }
  ]);
})();
