DROP TABLE IF EXISTS editorial_label_seed_0019;
CREATE TABLE editorial_label_seed_0019 (question_id TEXT PRIMARY KEY, player_name TEXT NOT NULL, season INTEGER NOT NULL, season_label TEXT NOT NULL, trait_id TEXT NOT NULL, verdict TEXT NOT NULL CHECK (verdict IN ('qualifies','does_not_qualify')), note TEXT);
INSERT INTO editorial_label_seed_0019 (question_id, player_name, season, season_label, trait_id, verdict, note) VALUES
  ('kareem-abdul-jabbar-1977-championship-number-one', 'Kareem Abdul-Jabbar', 1977, '1976-77', 'championship-number-one', 'qualifies', 'Won MVP while carrying Los Angeles as an elite two-way center.'),
  ('kareem-abdul-jabbar-1977-rim-protector', 'Kareem Abdul-Jabbar', 1977, '1976-77', 'rim-protector', 'qualifies', 'Blocked 3.2 shots and controlled the paint throughout his MVP season.'),
  ('kareem-abdul-jabbar-1977-playmaker', 'Kareem Abdul-Jabbar', 1977, '1976-77', 'playmaker', 'qualifies', 'Created open cuts and jumpers from constant post double-teams.'),
  ('julius-erving-1976-championship-number-one', 'Julius Erving', 1976, '1975-76', 'championship-number-one', 'qualifies', 'Won ABA MVP, playoff MVP, and the championship as New York''s engine.'),
  ('julius-erving-1976-rim-pressurer', 'Julius Erving', 1976, '1975-76', 'rim-pressurer', 'qualifies', 'Relentless open-court drives and aerial finishes collapsed every defense.'),
  ('julius-erving-1976-playmaker', 'Julius Erving', 1976, '1975-76', 'playmaker', 'qualifies', 'Averaged five assists while initiating offense from the wing.'),
  ('bill-walton-1978-championship-number-one', 'Bill Walton', 1978, '1977-78', 'championship-number-one', 'qualifies', 'League MVP and Portland''s organizing force before his foot injury.'),
  ('bill-walton-1978-team-defender', 'Bill Walton', 1978, '1977-78', 'team-defender', 'qualifies', 'Elite positioning, rebounding, and communication powered Portland''s defense.'),
  ('bill-walton-1978-rim-protector', 'Bill Walton', 1978, '1977-78', 'rim-protector', 'qualifies', 'Contested everything inside while averaging 2.5 blocks.'),
  ('rick-barry-1975-playmaker', 'Rick Barry', 1975, '1974-75', 'playmaker', 'qualifies', 'Averaged 6.2 assists while directing a championship offense.'),
  ('rick-barry-1975-tough-shot-maker', 'Rick Barry', 1975, '1974-75', 'tough-shot-maker', 'qualifies', 'Scored 30.6 nightly through contested jumpers and crafty finishes.'),
  ('walt-frazier-1975-iso-defender', 'Walt Frazier', 1975, '1974-75', 'iso-defender', 'qualifies', 'Still hounded lead guards with strength, hands, and anticipation.'),
  ('walt-frazier-1975-playmaker', 'Walt Frazier', 1975, '1974-75', 'playmaker', 'qualifies', 'Averaged 6.1 assists while controlling New York''s half-court offense.'),
  ('walt-frazier-1975-clutch', 'Walt Frazier', 1975, '1974-75', 'clutch', 'qualifies', 'Remained New York''s trusted late-game organizer and shot creator.'),
  ('john-havlicek-1974-off-ball-scorer', 'John Havlicek', 1974, '1973-74', 'off-ball-scorer', 'qualifies', 'Constant cuts, curls, and transition sprints produced 22.6 points.'),
  ('john-havlicek-1974-team-defender', 'John Havlicek', 1974, '1973-74', 'team-defender', 'qualifies', 'All-Defense recognition reflected relentless help, pressure, and recovery.'),
  ('john-havlicek-1974-clutch', 'John Havlicek', 1974, '1973-74', 'clutch', 'qualifies', 'Delivered throughout Boston''s championship run and seven-game Finals victory.'),
  ('bob-mcadoo-1975-championship-number-one', 'Bob McAdoo', 1975, '1974-75', 'championship-number-one', 'qualifies', 'Won MVP after averaging 34.5 points and 14.1 rebounds.'),
  ('bob-mcadoo-1975-tough-shot-maker', 'Bob McAdoo', 1975, '1974-75', 'tough-shot-maker', 'qualifies', 'Scored from post-ups, face-ups, and contested midrange jumpers.'),
  ('bob-mcadoo-1975-iso-defender', 'Bob McAdoo', 1975, '1974-75', 'iso-defender', 'does_not_qualify', 'Scoring and rebounding outpaced his resistance against elite post centers.'),
  ('elvin-hayes-1978-team-defender', 'Elvin Hayes', 1978, '1977-78', 'team-defender', 'qualifies', 'Rebounding, durability, and interior help anchored Washington''s championship defense.'),
  ('elvin-hayes-1978-tough-shot-maker', 'Elvin Hayes', 1978, '1977-78', 'tough-shot-maker', 'qualifies', 'His turnaround jumper remained productive against set playoff defenses.'),
  ('elvin-hayes-1978-ball-stopper', 'Elvin Hayes', 1978, '1977-78', 'ball-stopper', 'qualifies', 'Possessions frequently ended with his post jumper rather than another pass.'),
  ('george-gervin-1979-tough-shot-maker', 'George Gervin', 1979, '1978-79', 'tough-shot-maker', 'qualifies', 'Won the scoring title with finger rolls and contested pull-ups.'),
  ('george-gervin-1979-championship-number-one', 'George Gervin', 1979, '1978-79', 'championship-number-one', 'qualifies', 'A 29.6-point scoring champion could credibly headline a title offense.'),
  ('george-gervin-1979-team-defender', 'George Gervin', 1979, '1978-79', 'team-defender', 'does_not_qualify', 'Elite scoring was not matched by consistent help defense or resistance.'),
  ('pete-maravich-1977-playmaker', 'Pete Maravich', 1977, '1976-77', 'playmaker', 'qualifies', 'Averaged 5.4 assists while creating unconventional passing angles.'),
  ('pete-maravich-1977-tough-shot-maker', 'Pete Maravich', 1977, '1976-77', 'tough-shot-maker', 'qualifies', 'Led the league in scoring through deep, improvised, contested attempts.'),
  ('pete-maravich-1977-ball-pounder', 'Pete Maravich', 1977, '1976-77', 'ball-pounder', 'qualifies', 'His elaborate creation required extended dribbling and possession time.'),
  ('artis-gilmore-1978-rim-protector', 'Artis Gilmore', 1978, '1977-78', 'rim-protector', 'qualifies', 'Size, reach, and 2.2 blocks made paint attacks costly.'),
  ('artis-gilmore-1978-team-defender', 'Artis Gilmore', 1978, '1977-78', 'team-defender', 'qualifies', 'Controlled defensive possessions through rebounding and interior positioning.'),
  ('artis-gilmore-1978-off-ball-scorer', 'Artis Gilmore', 1978, '1977-78', 'off-ball-scorer', 'qualifies', 'Deep seals, putbacks, and finishes generated efficient offense without dribbling.'),
  ('moses-malone-1979-championship-number-one', 'Moses Malone', 1979, '1978-79', 'championship-number-one', 'qualifies', 'Won MVP while dominating the glass and carrying Houston''s offense.'),
  ('moses-malone-1979-ball-stopper', 'Moses Malone', 1979, '1978-79', 'ball-stopper', 'qualifies', 'Averaged 1.8 assists as possessions repeatedly ended with his attacks.'),
  ('moses-malone-1979-playmaker', 'Moses Malone', 1979, '1978-79', 'playmaker', 'does_not_qualify', 'Rarely created advantages for teammates beyond offensive-rebound pressure.'),
  ('david-thompson-1978-off-ball-scorer', 'David Thompson', 1978, '1977-78', 'off-ball-scorer', 'qualifies', 'Explosive cuts and transition runs created points before he needed dribbles.'),
  ('david-thompson-1978-championship-number-one', 'David Thompson', 1978, '1977-78', 'championship-number-one', 'qualifies', 'A 27.1-point superstar could plausibly lead a championship offense.'),
  ('david-thompson-1978-team-defender', 'David Thompson', 1978, '1977-78', 'team-defender', 'does_not_qualify', 'Scoring brilliance was not accompanied by dependable team-defense impact.'),
  ('maurice-lucas-1977-team-defender', 'Maurice Lucas', 1977, '1976-77', 'team-defender', 'qualifies', 'Physical help defense and rebounding gave Portland its championship edge.'),
  ('maurice-lucas-1977-clutch', 'Maurice Lucas', 1977, '1976-77', 'clutch', 'qualifies', 'Supplied reliable late-clock scoring throughout Portland''s title run.'),
  ('maurice-lucas-1977-playmaker', 'Maurice Lucas', 1977, '1976-77', 'playmaker', 'does_not_qualify', 'His offensive value came from scoring, screens, and rebounding, not creation.'),
  ('bobby-jones-1977-team-defender', 'Bobby Jones', 1977, '1976-77', 'team-defender', 'qualifies', 'Relentless rotations and recovery made Denver''s defense substantially better.'),
  ('bobby-jones-1977-switchable-defender', 'Bobby Jones', 1977, '1976-77', 'switchable-defender', 'qualifies', 'Comfortably handled wings, forwards, and many centers.'),
  ('bobby-jones-1977-championship-number-one', 'Bobby Jones', 1977, '1976-77', 'championship-number-one', 'does_not_qualify', 'Elite complementary impact lacked primary championship-level shot creation.'),
  ('magic-johnson-1987-playmaker', 'Magic Johnson', 1987, '1986-87', 'playmaker', 'qualifies', 'Averaged 12.2 assists and manufactured transition advantages every possession.'),
  ('magic-johnson-1987-iso-defender', 'Magic Johnson', 1987, '1986-87', 'iso-defender', 'does_not_qualify', 'Size helped, but quicker guards could beat him one-on-one.'),
  ('larry-bird-1986-playmaker', 'Larry Bird', 1986, '1985-86', 'playmaker', 'qualifies', 'His passing punished doubles and unlocked Boston''s entire frontcourt.'),
  ('larry-bird-1986-clutch', 'Larry Bird', 1986, '1985-86', 'clutch', 'qualifies', 'Boston trusted his shotmaking and decisions in every high-leverage possession.'),
  ('isiah-thomas-1990-playmaker', 'Isiah Thomas', 1990, '1989-90', 'playmaker', 'qualifies', 'Averaged 9.4 assists while creating Detroit''s best offensive advantages.'),
  ('isiah-thomas-1990-super-three-point-shooter', 'Isiah Thomas', 1990, '1989-90', 'super-three-point-shooter', 'does_not_qualify', 'Shot 30.9 percent from three without game-plan-warping gravity.'),
  ('kevin-mchale-1987-championship-number-one', 'Kevin McHale', 1987, '1986-87', 'championship-number-one', 'qualifies', 'Averaged 26.1 points on extraordinary efficiency despite a broken foot.'),
  ('kevin-mchale-1987-tough-shot-maker', 'Kevin McHale', 1987, '1986-87', 'tough-shot-maker', 'qualifies', 'Converted contested post counters from either block with unmatched touch.'),
  ('kevin-mchale-1987-playmaker', 'Kevin McHale', 1987, '1986-87', 'playmaker', 'does_not_qualify', 'Boston''s offense slowed when his post touches became shot-only possessions.'),
  ('robert-parish-1984-rim-protector', 'Robert Parish', 1984, '1983-84', 'rim-protector', 'qualifies', 'Length and positioning deterred drives for the championship Celtics.'),
  ('robert-parish-1984-off-ball-scorer', 'Robert Parish', 1984, '1983-84', 'off-ball-scorer', 'qualifies', 'Rim runs, putbacks, and quick post seals required little possession time.'),
  ('robert-parish-1984-championship-number-one', 'Robert Parish', 1984, '1983-84', 'championship-number-one', 'does_not_qualify', 'Excellent two-way center, but not a title-level primary offensive engine.'),
  ('james-worthy-1988-off-ball-scorer', 'James Worthy', 1988, '1987-88', 'off-ball-scorer', 'qualifies', 'Cuts and transition sprints punished defenses focused on Magic and Kareem.'),
  ('james-worthy-1988-clutch', 'James Worthy', 1988, '1987-88', 'clutch', 'qualifies', 'Won Finals MVP after a Game Seven triple-double.'),
  ('james-worthy-1988-rim-pressurer', 'James Worthy', 1988, '1987-88', 'rim-pressurer', 'qualifies', 'Explosive first steps and transition attacks repeatedly reached the basket.'),
  ('dominique-wilkins-1986-rim-pressurer', 'Dominique Wilkins', 1986, '1985-86', 'rim-pressurer', 'qualifies', 'Relentless drives and finishes powered his 30.3-point scoring title.'),
  ('dominique-wilkins-1986-tough-shot-maker', 'Dominique Wilkins', 1986, '1985-86', 'tough-shot-maker', 'qualifies', 'Created difficult jumpers and finishes against loaded defenses.'),
  ('dominique-wilkins-1986-team-defender', 'Dominique Wilkins', 1986, '1985-86', 'team-defender', 'does_not_qualify', 'His offensive workload did not produce consistent rotations or help impact.'),
  ('alex-english-1983-off-ball-scorer', 'Alex English', 1983, '1982-83', 'off-ball-scorer', 'qualifies', 'Cutting, transition running, and quick catches fueled 28.4 points.'),
  ('alex-english-1983-tough-shot-maker', 'Alex English', 1983, '1982-83', 'tough-shot-maker', 'qualifies', 'Soft touch converted contested midrange attempts throughout his scoring-title season.'),
  ('alex-english-1983-team-defender', 'Alex English', 1983, '1982-83', 'team-defender', 'does_not_qualify', 'Denver''s pace amplified scoring, but his defense did not lift the unit.'),
  ('adrian-dantley-1984-rim-pressurer', 'Adrian Dantley', 1984, '1983-84', 'rim-pressurer', 'qualifies', 'Generated constant paint contact and nearly ten free throws nightly.'),
  ('adrian-dantley-1984-ball-stopper', 'Adrian Dantley', 1984, '1983-84', 'ball-stopper', 'qualifies', 'Methodical isolations consumed possessions and often ended without another pass.'),
  ('adrian-dantley-1984-team-defender', 'Adrian Dantley', 1984, '1983-84', 'team-defender', 'does_not_qualify', 'Thirty-point scoring did not offset weak rotations and limited defensive activity.'),
  ('bernard-king-1985-tough-shot-maker', 'Bernard King', 1985, '1984-85', 'tough-shot-maker', 'qualifies', 'Averaged 32.9 points through contested post-ups and pull-ups.'),
  ('bernard-king-1985-championship-number-one', 'Bernard King', 1985, '1984-85', 'championship-number-one', 'qualifies', 'His scoring peak was strong enough to headline a championship offense.'),
  ('bernard-king-1985-playmaker', 'Bernard King', 1985, '1984-85', 'playmaker', 'does_not_qualify', 'Scoring possessions rarely became sustained advantage creation for teammates.'),
  ('sidney-moncrief-1983-iso-defender', 'Sidney Moncrief', 1983, '1982-83', 'iso-defender', 'qualifies', 'Won Defensive Player of the Year by smothering elite perimeter scorers.'),
  ('sidney-moncrief-1983-team-defender', 'Sidney Moncrief', 1983, '1982-83', 'team-defender', 'qualifies', 'Pressure, help, and rebounding elevated Milwaukee''s entire defensive structure.'),
  ('sidney-moncrief-1983-rim-pressurer', 'Sidney Moncrief', 1983, '1982-83', 'rim-pressurer', 'qualifies', 'Powerful drives produced efficient scoring and heavy free-throw pressure.'),
  ('joe-dumars-1989-iso-defender', 'Joe Dumars', 1989, '1988-89', 'iso-defender', 'qualifies', 'Took primary assignments against Jordan and other elite guards.'),
  ('joe-dumars-1989-clutch', 'Joe Dumars', 1989, '1988-89', 'clutch', 'qualifies', 'Won Finals MVP with composed scoring and decision-making.'),
  ('joe-dumars-1989-off-ball-scorer', 'Joe Dumars', 1989, '1988-89', 'off-ball-scorer', 'qualifies', 'Spacing and timely cuts complemented Detroit''s guard-driven offense.'),
  ('dennis-johnson-1986-iso-defender', 'Dennis Johnson', 1986, '1985-86', 'iso-defender', 'qualifies', 'Handled opposing lead guards with strength and disciplined positioning.'),
  ('dennis-johnson-1986-team-defender', 'Dennis Johnson', 1986, '1985-86', 'team-defender', 'qualifies', 'Smart help and communication strengthened an already elite Boston defense.'),
  ('dennis-johnson-1986-clutch', 'Dennis Johnson', 1986, '1985-86', 'clutch', 'qualifies', 'Boston repeatedly trusted him for late-game shots and decisions.');
INSERT INTO editorial_label_seed_0019 (question_id, player_name, season, season_label, trait_id, verdict, note) VALUES
  ('mark-eaton-1989-rim-protector', 'Mark Eaton', 1989, '1988-89', 'rim-protector', 'qualifies', 'Won Defensive Player of the Year while blocking 3.8 shots.'),
  ('mark-eaton-1989-team-defender', 'Mark Eaton', 1989, '1988-89', 'team-defender', 'qualifies', 'Utah''s scheme depended on his enormous paint deterrence.'),
  ('mark-eaton-1989-switchable-defender', 'Mark Eaton', 1989, '1988-89', 'switchable-defender', 'does_not_qualify', 'Lateral limitations confined him to deep interior coverage.'),
  ('michael-cooper-1987-iso-defender', 'Michael Cooper', 1987, '1986-87', 'iso-defender', 'qualifies', 'Won Defensive Player of the Year guarding elite perimeter scorers.'),
  ('michael-cooper-1987-three-point-shooter', 'Michael Cooper', 1987, '1986-87', 'three-point-shooter', 'qualifies', 'Shot 38.5 percent from three on meaningful volume.'),
  ('michael-cooper-1987-championship-number-one', 'Michael Cooper', 1987, '1986-87', 'championship-number-one', 'does_not_qualify', 'Elite specialist lacked the scoring burden of a championship centerpiece.'),
  ('dale-ellis-1989-three-point-shooter', 'Dale Ellis', 1989, '1988-89', 'three-point-shooter', 'qualifies', 'Made 162 threes at 47.8 percent, demanding tight coverage.'),
  ('dale-ellis-1989-tough-shot-maker', 'Dale Ellis', 1989, '1988-89', 'tough-shot-maker', 'qualifies', 'Averaged 27.5 points through contested jumpers and quick releases.'),
  ('dale-ellis-1989-team-defender', 'Dale Ellis', 1989, '1988-89', 'team-defender', 'does_not_qualify', 'Scoring value far exceeded his impact on Seattle''s defensive structure.'),
  ('kiki-vandeweghe-1984-tough-shot-maker', 'Kiki Vandeweghe', 1984, '1983-84', 'tough-shot-maker', 'qualifies', 'Averaged 29.4 points through polished post and midrange scoring.'),
  ('kiki-vandeweghe-1984-ball-stopper', 'Kiki Vandeweghe', 1984, '1983-84', 'ball-stopper', 'qualifies', 'Possessions frequently narrowed into his isolation scoring package.'),
  ('kiki-vandeweghe-1984-team-defender', 'Kiki Vandeweghe', 1984, '1983-84', 'team-defender', 'does_not_qualify', 'His defense remained a major weakness despite elite scoring efficiency.'),
  ('world-b-free-1980-tough-shot-maker', 'World B. Free', 1980, '1979-80', 'tough-shot-maker', 'qualifies', 'Averaged 30.2 points through high-arcing, heavily contested jumpers.'),
  ('world-b-free-1980-rim-pressurer', 'World B. Free', 1980, '1979-80', 'rim-pressurer', 'qualifies', 'Frequent drives and contact generated heavy free-throw pressure.'),
  ('world-b-free-1980-ball-stopper', 'World B. Free', 1980, '1979-80', 'ball-stopper', 'qualifies', 'High-usage isolations routinely ended possessions with his shot.'),
  ('jack-sikma-1982-team-defender', 'Jack Sikma', 1982, '1981-82', 'team-defender', 'qualifies', 'Rebounding and positioning stabilized Seattle''s interior defense.'),
  ('jack-sikma-1982-playmaker', 'Jack Sikma', 1982, '1981-82', 'playmaker', 'qualifies', 'Passed effectively from the elbows and post, averaging 3.4 assists.'),
  ('jack-sikma-1982-championship-number-one', 'Jack Sikma', 1982, '1981-82', 'championship-number-one', 'does_not_qualify', 'All-Star two-way value lacked primary championship-level offensive creation.'),
  ('alvin-robertson-1986-iso-defender', 'Alvin Robertson', 1986, '1985-86', 'iso-defender', 'qualifies', 'Won Defensive Player of the Year with suffocating ball pressure.'),
  ('alvin-robertson-1986-team-defender', 'Alvin Robertson', 1986, '1985-86', 'team-defender', 'qualifies', 'Record steal production repeatedly blew up opposing offensive actions.'),
  ('alvin-robertson-1986-three-point-shooter', 'Alvin Robertson', 1986, '1985-86', 'three-point-shooter', 'does_not_qualify', 'His virtually absent outside shot provided no arc gravity.'),
  ('michael-jordan-1991-iso-defender', 'Michael Jordan', 1991, '1990-91', 'iso-defender', 'qualifies', 'First-team All-Defense pressure erased elite guards and wings.'),
  ('michael-jordan-1991-rim-pressurer', 'Michael Jordan', 1991, '1990-91', 'rim-pressurer', 'qualifies', 'Explosive drives and post attacks constantly collapsed defenses.'),
  ('hakeem-olajuwon-1994-team-defender', 'Hakeem Olajuwon', 1994, '1993-94', 'team-defender', 'qualifies', 'Houston''s championship defense revolved around his mobility and anticipation.'),
  ('hakeem-olajuwon-1994-tough-shot-maker', 'Hakeem Olajuwon', 1994, '1993-94', 'tough-shot-maker', 'qualifies', 'Dream Shake counters produced contested scores against elite playoff centers.'),
  ('david-robinson-1995-championship-number-one', 'David Robinson', 1995, '1994-95', 'championship-number-one', 'qualifies', 'Won MVP while carrying San Antonio to 62 wins.'),
  ('david-robinson-1995-rim-protector', 'David Robinson', 1995, '1994-95', 'rim-protector', 'qualifies', 'Blocked 3.2 shots and erased mistakes with extraordinary range.'),
  ('david-robinson-1995-clutch', 'David Robinson', 1995, '1994-95', 'clutch', 'does_not_qualify', 'His scoring and late execution fell sharply against Houston''s playoff pressure.'),
  ('charles-barkley-1993-championship-number-one', 'Charles Barkley', 1993, '1992-93', 'championship-number-one', 'qualifies', 'Won MVP and led Phoenix to the Finals.'),
  ('charles-barkley-1993-rim-pressurer', 'Charles Barkley', 1993, '1992-93', 'rim-pressurer', 'qualifies', 'Power, speed, and contact forced defenses to collapse inside.'),
  ('charles-barkley-1993-team-defender', 'Charles Barkley', 1993, '1992-93', 'team-defender', 'does_not_qualify', 'Defensive engagement and rotations fluctuated despite elite rebounding.'),
  ('karl-malone-1997-championship-number-one', 'Karl Malone', 1997, '1996-97', 'championship-number-one', 'qualifies', 'Won MVP and led Utah to the Finals.'),
  ('karl-malone-1997-rim-pressurer', 'Karl Malone', 1997, '1996-97', 'rim-pressurer', 'qualifies', 'Powerful rolls and post drives generated constant paint pressure.'),
  ('karl-malone-1997-clutch', 'Karl Malone', 1997, '1996-97', 'clutch', 'does_not_qualify', 'Late free throws and Finals execution faltered against Chicago.'),
  ('john-stockton-1995-playmaker', 'John Stockton', 1995, '1994-95', 'playmaker', 'qualifies', 'Averaged 12.3 assists with surgical pick-and-roll passing.'),
  ('john-stockton-1995-off-ball-scorer', 'John Stockton', 1995, '1994-95', 'off-ball-scorer', 'qualifies', 'Relocation shooting and timely cuts punished attention to Malone.'),
  ('john-stockton-1995-three-point-shooter', 'John Stockton', 1995, '1994-95', 'three-point-shooter', 'qualifies', 'Shot 44.9 percent from three and demanded arc respect.'),
  ('scottie-pippen-1994-championship-number-one', 'Scottie Pippen', 1994, '1993-94', 'championship-number-one', 'qualifies', 'Finished third in MVP voting while leading Chicago to 55 wins.'),
  ('scottie-pippen-1994-team-defender', 'Scottie Pippen', 1994, '1993-94', 'team-defender', 'qualifies', 'Help, pressure, and anticipation powered an elite defensive identity.'),
  ('scottie-pippen-1994-switchable-defender', 'Scottie Pippen', 1994, '1993-94', 'switchable-defender', 'qualifies', 'Credibly guarded point guards through power forwards.'),
  ('dennis-rodman-1992-team-defender', 'Dennis Rodman', 1992, '1991-92', 'team-defender', 'qualifies', 'Won Defensive Player of the Year through relentless help and rebounding.'),
  ('dennis-rodman-1992-switchable-defender', 'Dennis Rodman', 1992, '1991-92', 'switchable-defender', 'qualifies', 'Handled wings, forwards, and centers without breaking Detroit''s scheme.'),
  ('dennis-rodman-1992-championship-number-one', 'Dennis Rodman', 1992, '1991-92', 'championship-number-one', 'does_not_qualify', 'Transformative specialist offered almost no primary scoring creation.'),
  ('gary-payton-1996-iso-defender', 'Gary Payton', 1996, '1995-96', 'iso-defender', 'qualifies', 'Won Defensive Player of the Year by tormenting elite guards.'),
  ('gary-payton-1996-playmaker', 'Gary Payton', 1996, '1995-96', 'playmaker', 'qualifies', 'Averaged 7.5 assists while driving Seattle''s transition and half-court offense.'),
  ('gary-payton-1996-championship-number-one', 'Gary Payton', 1996, '1995-96', 'championship-number-one', 'qualifies', 'Best player on a 64-win Finals team with elite two-way impact.'),
  ('shawn-kemp-1996-rim-pressurer', 'Shawn Kemp', 1996, '1995-96', 'rim-pressurer', 'qualifies', 'Violent rolls and drives generated constant rim finishes and fouls.'),
  ('shawn-kemp-1996-off-ball-scorer', 'Shawn Kemp', 1996, '1995-96', 'off-ball-scorer', 'qualifies', 'Screens, cuts, lobs, and putbacks created major low-touch scoring.'),
  ('shawn-kemp-1996-playmaker', 'Shawn Kemp', 1996, '1995-96', 'playmaker', 'does_not_qualify', 'Averaged 2.2 assists and rarely organized offense for teammates.'),
  ('clyde-drexler-1992-championship-number-one', 'Clyde Drexler', 1992, '1991-92', 'championship-number-one', 'qualifies', 'Finished second in MVP voting and led Portland to the Finals.'),
  ('clyde-drexler-1992-rim-pressurer', 'Clyde Drexler', 1992, '1991-92', 'rim-pressurer', 'qualifies', 'Transition speed and long-stride drives compressed defenses.'),
  ('clyde-drexler-1992-playmaker', 'Clyde Drexler', 1992, '1991-92', 'playmaker', 'qualifies', 'Averaged 6.7 assists while creating from either guard spot.'),
  ('patrick-ewing-1990-championship-number-one', 'Patrick Ewing', 1990, '1989-90', 'championship-number-one', 'qualifies', 'Averaged 28.6 points with elite interior defense at his peak.'),
  ('patrick-ewing-1990-team-defender', 'Patrick Ewing', 1990, '1989-90', 'team-defender', 'qualifies', 'Anchored New York''s defense through contests, rebounding, and physicality.'),
  ('patrick-ewing-1990-playmaker', 'Patrick Ewing', 1990, '1989-90', 'playmaker', 'does_not_qualify', 'Post touches produced few teammate advantages beyond basic kick-outs.'),
  ('reggie-miller-1998-super-three-point-shooter', 'Reggie Miller', 1998, '1997-98', 'super-three-point-shooter', 'qualifies', 'Off-ball gravity warped Chicago''s playoff coverage far beyond his attempts.'),
  ('reggie-miller-1998-clutch', 'Reggie Miller', 1998, '1997-98', 'clutch', 'qualifies', 'Hit the conference-finals winner after creating separation from Jordan.'),
  ('reggie-miller-1998-iso-defender', 'Reggie Miller', 1998, '1997-98', 'iso-defender', 'does_not_qualify', 'Indiana protected him rather than assigning elite perimeter creators.'),
  ('grant-hill-1997-championship-number-one', 'Grant Hill', 1997, '1996-97', 'championship-number-one', 'qualifies', 'Finished third in MVP voting as Detroit''s complete offensive engine.'),
  ('grant-hill-1997-rim-pressurer', 'Grant Hill', 1997, '1996-97', 'rim-pressurer', 'qualifies', 'Powerful drives produced efficient paint scoring and free throws.'),
  ('grant-hill-1997-three-point-shooter', 'Grant Hill', 1997, '1996-97', 'three-point-shooter', 'does_not_qualify', 'Low-volume, inaccurate shooting allowed defenders to sag off him.'),
  ('anfernee-hardaway-1996-playmaker', 'Anfernee Hardaway', 1996, '1995-96', 'playmaker', 'qualifies', 'Averaged 7.1 assists while running Orlando''s offense without Shaq handling.'),
  ('anfernee-hardaway-1996-rim-pressurer', 'Anfernee Hardaway', 1996, '1995-96', 'rim-pressurer', 'qualifies', 'Size and burst created paint touches against smaller guards.'),
  ('anfernee-hardaway-1996-championship-number-one', 'Anfernee Hardaway', 1996, '1995-96', 'championship-number-one', 'qualifies', 'First-team All-NBA production supported a credible title-leading ceiling.'),
  ('dikembe-mutombo-1997-rim-protector', 'Dikembe Mutombo', 1997, '1996-97', 'rim-protector', 'qualifies', 'Won Defensive Player of the Year while blocking 3.3 shots.'),
  ('dikembe-mutombo-1997-team-defender', 'Dikembe Mutombo', 1997, '1996-97', 'team-defender', 'qualifies', 'Atlanta''s defensive identity centered on his paint deterrence and rebounding.'),
  ('dikembe-mutombo-1997-playmaker', 'Dikembe Mutombo', 1997, '1996-97', 'playmaker', 'does_not_qualify', 'Averaged 1.4 assists and offered minimal creation outside finishes.'),
  ('alonzo-mourning-1999-rim-protector', 'Alonzo Mourning', 1999, '1998-99', 'rim-protector', 'qualifies', 'Won Defensive Player of the Year with 3.9 blocks nightly.'),
  ('alonzo-mourning-1999-championship-number-one', 'Alonzo Mourning', 1999, '1998-99', 'championship-number-one', 'qualifies', 'Finished second in MVP voting while leading Miami''s two-way identity.'),
  ('alonzo-mourning-1999-playmaker', 'Alonzo Mourning', 1999, '1998-99', 'playmaker', 'does_not_qualify', 'Double-teams rarely became high-level passing advantages for Miami.'),
  ('tim-hardaway-1997-playmaker', 'Tim Hardaway', 1997, '1996-97', 'playmaker', 'qualifies', 'Averaged 8.6 assists while orchestrating Miami''s half-court offense.'),
  ('tim-hardaway-1997-three-point-shooter', 'Tim Hardaway', 1997, '1996-97', 'three-point-shooter', 'qualifies', 'High-volume pull-up threes forced defenders over every screen.'),
  ('tim-hardaway-1997-iso-defender', 'Tim Hardaway', 1997, '1996-97', 'iso-defender', 'does_not_qualify', 'Miami''s scheme covered his size limitations against bigger guards.'),
  ('mark-price-1994-three-point-shooter', 'Mark Price', 1994, '1993-94', 'three-point-shooter', 'qualifies', 'Shot 39.7 percent on high-value pull-ups and spot-ups.'),
  ('mark-price-1994-playmaker', 'Mark Price', 1994, '1993-94', 'playmaker', 'qualifies', 'Averaged 7.8 assists through precise pick-and-roll reads.'),
  ('mark-price-1994-clutch', 'Mark Price', 1994, '1993-94', 'clutch', 'qualifies', 'Cleveland trusted his shooting and decisions in late-clock possessions.'),
  ('chris-mullin-1990-off-ball-scorer', 'Chris Mullin', 1990, '1989-90', 'off-ball-scorer', 'qualifies', 'Cuts, relocations, and quick catches complemented his 25.1-point season.'),
  ('chris-mullin-1990-tough-shot-maker', 'Chris Mullin', 1990, '1989-90', 'tough-shot-maker', 'qualifies', 'Elite touch converted contested midrange attempts from awkward angles.'),
  ('chris-mullin-1990-team-defender', 'Chris Mullin', 1990, '1989-90', 'team-defender', 'does_not_qualify', 'Golden State''s defense received little lift from his rotations or pressure.'),
  ('mitch-richmond-1997-three-point-shooter', 'Mitch Richmond', 1997, '1996-97', 'three-point-shooter', 'qualifies', 'Made 204 threes while shooting 42.8 percent.');
INSERT INTO editorial_label_seed_0019 (question_id, player_name, season, season_label, trait_id, verdict, note) VALUES
  ('mitch-richmond-1997-tough-shot-maker', 'Mitch Richmond', 1997, '1996-97', 'tough-shot-maker', 'qualifies', 'Averaged 25.9 points despite carrying Sacramento''s difficult shot burden.'),
  ('mitch-richmond-1997-playmaker', 'Mitch Richmond', 1997, '1996-97', 'playmaker', 'does_not_qualify', 'His scoring gravity produced only modest advantage creation for teammates.'),
  ('arvydas-sabonis-1996-playmaker', 'Arvydas Sabonis', 1996, '1995-96', 'playmaker', 'qualifies', 'Advanced passing vision created cuts and open shots from the post.'),
  ('arvydas-sabonis-1996-rim-protector', 'Arvydas Sabonis', 1996, '1995-96', 'rim-protector', 'qualifies', 'Size, timing, and positioning discouraged paint attacks despite limited mobility.'),
  ('arvydas-sabonis-1996-team-defender', 'Arvydas Sabonis', 1996, '1995-96', 'team-defender', 'qualifies', 'Portland improved through his rebounding, communication, and interior positioning.'),
  ('toni-kukoc-1996-playmaker', 'Toni Kukoc', 1996, '1995-96', 'playmaker', 'qualifies', 'Secondary creation connected Chicago''s stars and second unit.'),
  ('toni-kukoc-1996-off-ball-scorer', 'Toni Kukoc', 1996, '1995-96', 'off-ball-scorer', 'qualifies', 'Cutting and spot-up shooting punished attention devoted to Jordan and Pippen.'),
  ('toni-kukoc-1996-iso-defender', 'Toni Kukoc', 1996, '1995-96', 'iso-defender', 'does_not_qualify', 'Chicago avoided using him as the primary answer for elite scorers.'),
  ('mookie-blaylock-1997-iso-defender', 'Mookie Blaylock', 1997, '1996-97', 'iso-defender', 'qualifies', 'First-team All-Defense pressure disrupted opposing point guards.'),
  ('mookie-blaylock-1997-team-defender', 'Mookie Blaylock', 1997, '1996-97', 'team-defender', 'qualifies', 'Steals and rotations powered Atlanta''s elite defensive performance.'),
  ('mookie-blaylock-1997-playmaker', 'Mookie Blaylock', 1997, '1996-97', 'playmaker', 'qualifies', 'Averaged 5.9 assists while balancing scoring and setup duties.'),
  ('horace-grant-1994-team-defender', 'Horace Grant', 1994, '1993-94', 'team-defender', 'qualifies', 'Rebounding, help, and mobility supported Chicago''s post-Jordan defense.'),
  ('horace-grant-1994-off-ball-scorer', 'Horace Grant', 1994, '1993-94', 'off-ball-scorer', 'qualifies', 'Screening, cuts, and midrange finishes fit seamlessly beside Pippen.'),
  ('horace-grant-1994-championship-number-one', 'Horace Grant', 1994, '1993-94', 'championship-number-one', 'does_not_qualify', 'High-level complementary production lacked primary shot creation.'),
  ('shaquille-o-neal-2000-rim-pressurer', 'Shaquille O''Neal', 2000, '1999-00', 'rim-pressurer', 'qualifies', 'Deep seals and power finishes forced constant doubles and fouls.'),
  ('shaquille-o-neal-2000-three-point-shooter', 'Shaquille O''Neal', 2000, '1999-00', 'three-point-shooter', 'does_not_qualify', 'Attempted no threes; defenses ignored him beyond the paint.'),
  ('kobe-bryant-2006-championship-number-one', 'Kobe Bryant', 2006, '2005-06', 'championship-number-one', 'qualifies', 'Averaged 35.4 points with title-caliber primary scoring talent.'),
  ('kobe-bryant-2006-ball-pounder', 'Kobe Bryant', 2006, '2005-06', 'ball-pounder', 'qualifies', 'Isolation creation often required extended dribbling against set defenses.'),
  ('tim-duncan-2003-rim-protector', 'Tim Duncan', 2003, '2002-03', 'rim-protector', 'qualifies', 'Blocked 2.9 shots and erased mistakes without chasing highlights.'),
  ('tim-duncan-2003-team-defender', 'Tim Duncan', 2003, '2002-03', 'team-defender', 'qualifies', 'Positioning and communication anchored an elite championship defense.'),
  ('kevin-garnett-2004-championship-number-one', 'Kevin Garnett', 2004, '2003-04', 'championship-number-one', 'qualifies', 'Won MVP while leading Minnesota to 58 wins and the conference finals.'),
  ('kevin-garnett-2004-switchable-defender', 'Kevin Garnett', 2004, '2003-04', 'switchable-defender', 'qualifies', 'Could credibly defend guards, wings, forwards, and centers.'),
  ('kevin-garnett-2004-playmaker', 'Kevin Garnett', 2004, '2003-04', 'playmaker', 'qualifies', 'Averaged five assists while creating from elbows, post, and transition.'),
  ('allen-iverson-2001-championship-number-one', 'Allen Iverson', 2001, '2000-01', 'championship-number-one', 'qualifies', 'Won MVP and carried Philadelphia to the Finals.'),
  ('allen-iverson-2001-rim-pressurer', 'Allen Iverson', 2001, '2000-01', 'rim-pressurer', 'qualifies', 'Relentless speed generated paint touches and nearly ten free throws nightly.'),
  ('allen-iverson-2001-ball-stopper', 'Allen Iverson', 2001, '2000-01', 'ball-stopper', 'qualifies', 'League-leading usage and shot volume frequently ended possessions with him.'),
  ('tracy-mcgrady-2003-championship-number-one', 'Tracy McGrady', 2003, '2002-03', 'championship-number-one', 'qualifies', 'A 32.1-point scoring champion had clear title-leading offensive ability.'),
  ('tracy-mcgrady-2003-playmaker', 'Tracy McGrady', 2003, '2002-03', 'playmaker', 'qualifies', 'Averaged 5.5 assists while creating advantages from either wing.'),
  ('tracy-mcgrady-2003-team-defender', 'Tracy McGrady', 2003, '2002-03', 'team-defender', 'does_not_qualify', 'Orlando''s defense received inconsistent effort and little organizing impact.'),
  ('vince-carter-2001-rim-pressurer', 'Vince Carter', 2001, '2000-01', 'rim-pressurer', 'qualifies', 'Explosive drives and finishes forced defenses to crowd the paint.'),
  ('vince-carter-2001-tough-shot-maker', 'Vince Carter', 2001, '2000-01', 'tough-shot-maker', 'qualifies', 'Averaged 27.6 through contested jumpers and acrobatic finishes.'),
  ('vince-carter-2001-team-defender', 'Vince Carter', 2001, '2000-01', 'team-defender', 'does_not_qualify', 'His athletic tools did not consistently elevate Toronto''s defensive structure.'),
  ('jason-kidd-2002-playmaker', 'Jason Kidd', 2002, '2001-02', 'playmaker', 'qualifies', 'Averaged 9.9 assists and transformed New Jersey''s transition offense.'),
  ('jason-kidd-2002-team-defender', 'Jason Kidd', 2002, '2001-02', 'team-defender', 'qualifies', 'Rebounding, help, and anticipation powered the conference''s best defense.'),
  ('jason-kidd-2002-three-point-shooter', 'Jason Kidd', 2002, '2001-02', 'three-point-shooter', 'does_not_qualify', 'Shot 32.1 percent as defenders routinely went under screens.'),
  ('ray-allen-2001-three-point-shooter', 'Ray Allen', 2001, '2000-01', 'three-point-shooter', 'qualifies', 'Made 202 threes at 43.3 percent on demanding attempts.'),
  ('ray-allen-2001-off-ball-scorer', 'Ray Allen', 2001, '2000-01', 'off-ball-scorer', 'qualifies', 'Relocations and quick releases produced major scoring without prolonged possession.'),
  ('ray-allen-2001-clutch', 'Ray Allen', 2001, '2000-01', 'clutch', 'qualifies', 'Milwaukee trusted his shooting and composure in high-leverage playoff possessions.'),
  ('paul-pierce-2002-tough-shot-maker', 'Paul Pierce', 2002, '2001-02', 'tough-shot-maker', 'qualifies', 'Averaged 26.1 through physical drives and contested pull-ups.'),
  ('paul-pierce-2002-rim-pressurer', 'Paul Pierce', 2002, '2001-02', 'rim-pressurer', 'qualifies', 'Strength and footwork produced paint touches and heavy free-throw volume.'),
  ('paul-pierce-2002-championship-number-one', 'Paul Pierce', 2002, '2001-02', 'championship-number-one', 'qualifies', 'Led Boston to the conference finals as a credible primary star.'),
  ('dirk-nowitzki-2007-championship-number-one', 'Dirk Nowitzki', 2007, '2006-07', 'championship-number-one', 'qualifies', 'Won MVP while leading Dallas to 67 wins.'),
  ('dirk-nowitzki-2007-super-three-point-shooter', 'Dirk Nowitzki', 2007, '2006-07', 'super-three-point-shooter', 'qualifies', 'A seven-footer''s shooting forced bigs far outside normal defensive structure.'),
  ('dirk-nowitzki-2007-tough-shot-maker', 'Dirk Nowitzki', 2007, '2006-07', 'tough-shot-maker', 'qualifies', 'One-legged fades and high-release jumpers defeated elite contests.'),
  ('steve-nash-2006-playmaker', 'Steve Nash', 2006, '2005-06', 'playmaker', 'qualifies', 'Won MVP while directing the league''s most efficient offense.'),
  ('steve-nash-2006-super-three-point-shooter', 'Steve Nash', 2006, '2005-06', 'super-three-point-shooter', 'qualifies', 'Pull-up and relocation shooting distorted pick-and-roll coverage.'),
  ('steve-nash-2006-iso-defender', 'Steve Nash', 2006, '2005-06', 'iso-defender', 'does_not_qualify', 'Opponents targeted his size and limited resistance one-on-one.'),
  ('dwyane-wade-2009-championship-number-one', 'Dwyane Wade', 2009, '2008-09', 'championship-number-one', 'qualifies', 'Averaged 30.2 points with elite creation and two-way impact.'),
  ('dwyane-wade-2009-rim-pressurer', 'Dwyane Wade', 2009, '2008-09', 'rim-pressurer', 'qualifies', 'Explosive drives produced constant paint collapses and free throws.'),
  ('dwyane-wade-2009-playmaker', 'Dwyane Wade', 2009, '2008-09', 'playmaker', 'qualifies', 'Averaged 7.5 assists while creating nearly every Miami advantage.'),
  ('lebron-james-2009-championship-number-one', 'LeBron James', 2009, '2008-09', 'championship-number-one', 'qualifies', 'Won MVP and led Cleveland to 66 wins.'),
  ('lebron-james-2009-rim-pressurer', 'LeBron James', 2009, '2008-09', 'rim-pressurer', 'qualifies', 'Transition force and downhill drives overwhelmed every defensive shell.'),
  ('lebron-james-2009-playmaker', 'LeBron James', 2009, '2008-09', 'playmaker', 'qualifies', 'Averaged 7.2 assists while orchestrating Cleveland''s entire offense.'),
  ('chris-paul-2008-championship-number-one', 'Chris Paul', 2008, '2007-08', 'championship-number-one', 'qualifies', 'Finished second in MVP voting while leading New Orleans to 56 wins.'),
  ('chris-paul-2008-iso-defender', 'Chris Paul', 2008, '2007-08', 'iso-defender', 'qualifies', 'First-team All-Defense pressure and hands disrupted opposing guards.'),
  ('dwight-howard-2009-rim-protector', 'Dwight Howard', 2009, '2008-09', 'rim-protector', 'qualifies', 'Won Defensive Player of the Year while anchoring a Finals defense.'),
  ('dwight-howard-2009-team-defender', 'Dwight Howard', 2009, '2008-09', 'team-defender', 'qualifies', 'Orlando''s scheme depended on his range, rebounding, and deterrence.'),
  ('dwight-howard-2009-off-ball-scorer', 'Dwight Howard', 2009, '2008-09', 'off-ball-scorer', 'qualifies', 'Rolls, lobs, putbacks, and seals created efficient low-touch scoring.'),
  ('yao-ming-2007-tough-shot-maker', 'Yao Ming', 2007, '2006-07', 'tough-shot-maker', 'qualifies', 'Soft touch converted contested hooks and turnaround jumpers over doubles.'),
  ('yao-ming-2007-rim-protector', 'Yao Ming', 2007, '2006-07', 'rim-protector', 'qualifies', 'Size and positioning deterred shots even without elite mobility.'),
  ('yao-ming-2007-switchable-defender', 'Yao Ming', 2007, '2006-07', 'switchable-defender', 'does_not_qualify', 'Perimeter switches exposed his foot speed and recovery limitations.'),
  ('pau-gasol-2009-playmaker', 'Pau Gasol', 2009, '2008-09', 'playmaker', 'qualifies', 'High-post passing connected Los Angeles'' cutters and weak-side shooters.'),
  ('pau-gasol-2009-off-ball-scorer', 'Pau Gasol', 2009, '2008-09', 'off-ball-scorer', 'qualifies', 'Screens, cuts, and quick seals complemented Kobe without monopolizing possessions.'),
  ('pau-gasol-2009-championship-number-one', 'Pau Gasol', 2009, '2008-09', 'championship-number-one', 'does_not_qualify', 'Elite second star lacked the primary perimeter creation of a centerpiece.'),
  ('manu-ginobili-2008-playmaker', 'Manu Ginobili', 2008, '2007-08', 'playmaker', 'qualifies', 'Inventive passing created advantages for starters and bench units alike.'),
  ('manu-ginobili-2008-rim-pressurer', 'Manu Ginobili', 2008, '2007-08', 'rim-pressurer', 'qualifies', 'Left-handed drives and Eurosteps repeatedly broke the paint.'),
  ('manu-ginobili-2008-clutch', 'Manu Ginobili', 2008, '2007-08', 'clutch', 'qualifies', 'San Antonio trusted his improvisation in high-leverage possessions.'),
  ('tony-parker-2009-rim-pressurer', 'Tony Parker', 2009, '2008-09', 'rim-pressurer', 'qualifies', 'Speed and touch produced league-leading paint pressure among guards.'),
  ('tony-parker-2009-playmaker', 'Tony Parker', 2009, '2008-09', 'playmaker', 'qualifies', 'Averaged 6.9 assists while driving San Antonio''s pick-and-roll offense.'),
  ('tony-parker-2009-team-defender', 'Tony Parker', 2009, '2008-09', 'team-defender', 'does_not_qualify', 'His size and screen navigation did not elevate San Antonio''s defense.'),
  ('chauncey-billups-2006-playmaker', 'Chauncey Billups', 2006, '2005-06', 'playmaker', 'qualifies', 'Averaged 8.6 assists with elite control and low turnover risk.'),
  ('chauncey-billups-2006-clutch', 'Chauncey Billups', 2006, '2005-06', 'clutch', 'qualifies', 'Detroit consistently trusted his pull-ups, post-ups, and free throws late.'),
  ('chauncey-billups-2006-championship-number-one', 'Chauncey Billups', 2006, '2005-06', 'championship-number-one', 'qualifies', 'Finished fifth in MVP voting while leading a 64-win contender.'),
  ('ben-wallace-2004-iso-defender', 'Ben Wallace', 2004, '2003-04', 'iso-defender', 'qualifies', 'Strength and quickness let him stonewall elite big men one-on-one.'),
  ('ben-wallace-2004-switchable-defender', 'Ben Wallace', 2004, '2003-04', 'switchable-defender', 'qualifies', 'Could survive against guards while overpowering centers.'),
  ('ben-wallace-2004-championship-number-one', 'Ben Wallace', 2004, '2003-04', 'championship-number-one', 'does_not_qualify', 'Championship-defining defense came without primary scoring or creation.'),
  ('rasheed-wallace-2004-switchable-defender', 'Rasheed Wallace', 2004, '2003-04', 'switchable-defender', 'qualifies', 'Mobility and length let Detroit switch across frontcourt matchups.'),
  ('rasheed-wallace-2004-three-point-shooter', 'Rasheed Wallace', 2004, '2003-04', 'three-point-shooter', 'qualifies', 'Stretch shooting pulled opposing bigs away from the paint.'),
  ('rasheed-wallace-2004-championship-number-one', 'Rasheed Wallace', 2004, '2003-04', 'championship-number-one', 'does_not_qualify', 'Versatile two-way impact remained better suited to a supporting-star role.'),
  ('metta-world-peace-2004-iso-defender', 'Metta World Peace', 2004, '2003-04', 'iso-defender', 'qualifies', 'Won Defensive Player of the Year while handling elite wings.');
INSERT INTO editorial_label_seed_0019 (question_id, player_name, season, season_label, trait_id, verdict, note) VALUES
  ('metta-world-peace-2004-team-defender', 'Metta World Peace', 2004, '2003-04', 'team-defender', 'qualifies', 'Physicality, help, and disruption anchored Indiana''s league-best defense.'),
  ('metta-world-peace-2004-playmaker', 'Metta World Peace', 2004, '2003-04', 'playmaker', 'does_not_qualify', 'He rarely bent defenses as a consistent creator for teammates.'),
  ('amar-e-stoudemire-2005-rim-pressurer', 'Amar''e Stoudemire', 2005, '2004-05', 'rim-pressurer', 'qualifies', 'Explosive rolls and face-up drives relentlessly attacked the rim.'),
  ('amar-e-stoudemire-2005-tough-shot-maker', 'Amar''e Stoudemire', 2005, '2004-05', 'tough-shot-maker', 'qualifies', 'Face-up jumpers and explosive finishes survived increasingly loaded playoff coverage.'),
  ('amar-e-stoudemire-2005-team-defender', 'Amar''e Stoudemire', 2005, '2004-05', 'team-defender', 'does_not_qualify', 'Poor positioning and awareness limited Phoenix''s defensive ceiling.'),
  ('shawn-marion-2006-off-ball-scorer', 'Shawn Marion', 2006, '2005-06', 'off-ball-scorer', 'qualifies', 'Cuts, transition runs, offensive rebounds, and quick threes required few touches.'),
  ('shawn-marion-2006-switchable-defender', 'Shawn Marion', 2006, '2005-06', 'switchable-defender', 'qualifies', 'Credibly guarded guards, wings, forwards, and smaller centers.'),
  ('shawn-marion-2006-tough-shot-maker', 'Shawn Marion', 2006, '2005-06', 'tough-shot-maker', 'does_not_qualify', 'Scoring depended on advantages rather than difficult self-created attempts.'),
  ('peja-stojakovic-2004-super-three-point-shooter', 'Peja Stojakovic', 2004, '2003-04', 'super-three-point-shooter', 'qualifies', 'Movement shooting forced defenses to trail him far beyond the arc.'),
  ('peja-stojakovic-2004-off-ball-scorer', 'Peja Stojakovic', 2004, '2003-04', 'off-ball-scorer', 'qualifies', 'Relocations and curls generated 24.2 points with minimal dribbling.'),
  ('peja-stojakovic-2004-iso-defender', 'Peja Stojakovic', 2004, '2003-04', 'iso-defender', 'does_not_qualify', 'Sacramento avoided assigning him the opponent''s strongest perimeter scorer.'),
  ('gilbert-arenas-2006-ball-pounder', 'Gilbert Arenas', 2006, '2005-06', 'ball-pounder', 'qualifies', 'High-usage isolation creation required extended dribbling and possession control.'),
  ('gilbert-arenas-2006-clutch', 'Gilbert Arenas', 2006, '2005-06', 'clutch', 'qualifies', 'Repeatedly delivered deep pull-ups and free throws in late-game situations.'),
  ('gilbert-arenas-2006-team-defender', 'Gilbert Arenas', 2006, '2005-06', 'team-defender', 'does_not_qualify', 'Washington''s defense gained little from his effort, rotations, or communication.'),
  ('baron-davis-2007-playmaker', 'Baron Davis', 2007, '2006-07', 'playmaker', 'qualifies', 'Averaged 8.1 assists while powering Golden State''s aggressive offense.'),
  ('baron-davis-2007-rim-pressurer', 'Baron Davis', 2007, '2006-07', 'rim-pressurer', 'qualifies', 'Strength and burst created paint touches against Dallas'' defense.'),
  ('baron-davis-2007-tough-shot-maker', 'Baron Davis', 2007, '2006-07', 'tough-shot-maker', 'qualifies', 'Hit difficult pull-ups throughout the historic first-round upset.'),
  ('brandon-roy-2009-playmaker', 'Brandon Roy', 2009, '2008-09', 'playmaker', 'qualifies', 'Averaged 5.1 assists as Portland''s primary advantage creator.'),
  ('brandon-roy-2009-tough-shot-maker', 'Brandon Roy', 2009, '2008-09', 'tough-shot-maker', 'qualifies', 'Controlled games with contested pull-ups and late-clock isolations.'),
  ('brandon-roy-2009-championship-number-one', 'Brandon Roy', 2009, '2008-09', 'championship-number-one', 'qualifies', 'Second-team All-NBA creation supported a credible title-leading ceiling.'),
  ('stephen-curry-2016-championship-number-one', 'Stephen Curry', 2016, '2015-16', 'championship-number-one', 'qualifies', 'Unanimous MVP led a record 73-win team and historic offense.'),
  ('stephen-curry-2016-playmaker', 'Stephen Curry', 2016, '2015-16', 'playmaker', 'qualifies', 'Drives, passing, and gravity created advantages before teammates received the ball.'),
  ('stephen-curry-2016-team-defender', 'Stephen Curry', 2016, '2015-16', 'team-defender', 'does_not_qualify', 'Smart within the scheme, but not a primary driver of elite defense.'),
  ('kevin-durant-2014-championship-number-one', 'Kevin Durant', 2014, '2013-14', 'championship-number-one', 'qualifies', 'Won MVP after averaging 32 points with elite efficiency.'),
  ('kevin-durant-2014-rim-pressurer', 'Kevin Durant', 2014, '2013-14', 'rim-pressurer', 'qualifies', 'Long strides and finishing generated eight free throws per game.'),
  ('kevin-durant-2014-super-three-point-shooter', 'Kevin Durant', 2014, '2013-14', 'super-three-point-shooter', 'qualifies', 'Pull-up range forced defenders to extend well beyond normal forward coverage.'),
  ('james-harden-2019-ball-pounder', 'James Harden', 2019, '2018-19', 'ball-pounder', 'qualifies', 'Historic isolation volume demanded prolonged control of Houston''s possessions.'),
  ('james-harden-2019-championship-number-one', 'James Harden', 2019, '2018-19', 'championship-number-one', 'qualifies', 'A 36.1-point MVP runner-up could credibly lead a champion.'),
  ('russell-westbrook-2017-ball-pounder', 'Russell Westbrook', 2017, '2016-17', 'ball-pounder', 'qualifies', 'Record usage required extended dribbling and control on nearly every possession.'),
  ('russell-westbrook-2017-championship-number-one', 'Russell Westbrook', 2017, '2016-17', 'championship-number-one', 'does_not_qualify', 'Extreme inefficiency and decision volatility limited championship-leading credibility.'),
  ('kawhi-leonard-2017-championship-number-one', 'Kawhi Leonard', 2017, '2016-17', 'championship-number-one', 'qualifies', 'Finished third in MVP voting with elite two-way playoff production.'),
  ('kawhi-leonard-2017-iso-defender', 'Kawhi Leonard', 2017, '2016-17', 'iso-defender', 'qualifies', 'Still erased elite wings with strength, hands, and positioning.'),
  ('kawhi-leonard-2017-tough-shot-maker', 'Kawhi Leonard', 2017, '2016-17', 'tough-shot-maker', 'qualifies', 'Converted contested pull-ups and post fades at superstar efficiency.'),
  ('giannis-antetokounmpo-2020-championship-number-one', 'Giannis Antetokounmpo', 2020, '2019-20', 'championship-number-one', 'qualifies', 'Won MVP and Defensive Player while leading Milwaukee to 56 wins.'),
  ('giannis-antetokounmpo-2020-rim-pressurer', 'Giannis Antetokounmpo', 2020, '2019-20', 'rim-pressurer', 'qualifies', 'Transition and half-court drives created overwhelming paint collapse.'),
  ('giannis-antetokounmpo-2020-three-point-shooter', 'Giannis Antetokounmpo', 2020, '2019-20', 'three-point-shooter', 'does_not_qualify', 'Shot 30.4 percent as playoff defenses deliberately conceded threes.'),
  ('anthony-davis-2015-rim-protector', 'Anthony Davis', 2015, '2014-15', 'rim-protector', 'qualifies', 'Blocked 2.9 shots with elite recovery range and timing.'),
  ('anthony-davis-2015-championship-number-one', 'Anthony Davis', 2015, '2014-15', 'championship-number-one', 'qualifies', 'Finished fifth in MVP voting with dominant two-way production.'),
  ('anthony-davis-2015-playmaker', 'Anthony Davis', 2015, '2014-15', 'playmaker', 'does_not_qualify', 'Averaged 2.2 assists and rarely organized advantages for teammates.'),
  ('damian-lillard-2020-championship-number-one', 'Damian Lillard', 2020, '2019-20', 'championship-number-one', 'qualifies', 'Averaged 30 points with the shotmaking to lead a title offense.'),
  ('damian-lillard-2020-playmaker', 'Damian Lillard', 2020, '2019-20', 'playmaker', 'qualifies', 'Averaged eight assists while forcing traps far above the arc.'),
  ('damian-lillard-2020-iso-defender', 'Damian Lillard', 2020, '2019-20', 'iso-defender', 'does_not_qualify', 'Opponents targeted his size and limited resistance in isolation.'),
  ('klay-thompson-2016-team-defender', 'Klay Thompson', 2016, '2015-16', 'team-defender', 'qualifies', 'Screen navigation and low-error rotations supported Golden State''s elite defense.'),
  ('klay-thompson-2016-playmaker', 'Klay Thompson', 2016, '2015-16', 'playmaker', 'does_not_qualify', 'Averaged 2.1 assists and rarely created advantages off the dribble.'),
  ('klay-thompson-2016-championship-number-one', 'Klay Thompson', 2016, '2015-16', 'championship-number-one', 'does_not_qualify', 'Elite scoring specialist lacked primary creation and all-around offensive control.'),
  ('draymond-green-2016-team-defender', 'Draymond Green', 2016, '2015-16', 'team-defender', 'qualifies', 'Communication and anticipation organized Golden State''s switching defense.'),
  ('draymond-green-2016-rim-protector', 'Draymond Green', 2016, '2015-16', 'rim-protector', 'qualifies', 'Undersized verticality and timing still deterred and altered interior shots.'),
  ('draymond-green-2016-tough-shot-maker', 'Draymond Green', 2016, '2015-16', 'tough-shot-maker', 'does_not_qualify', 'Scoring depended on open threes, cuts, and short-roll advantages.'),
  ('jimmy-butler-2020-championship-number-one', 'Jimmy Butler', 2020, '2019-20', 'championship-number-one', 'qualifies', 'Led Miami to the Finals with elite two-way playoff creation.'),
  ('jimmy-butler-2020-playmaker', 'Jimmy Butler', 2020, '2019-20', 'playmaker', 'qualifies', 'Averaged six assists and repeatedly created paint-to-perimeter advantages.'),
  ('jimmy-butler-2020-three-point-shooter', 'Jimmy Butler', 2020, '2019-20', 'three-point-shooter', 'does_not_qualify', 'Shot 24.4 percent as defenses willingly conceded outside attempts.'),
  ('paul-george-2019-championship-number-one', 'Paul George', 2019, '2018-19', 'championship-number-one', 'qualifies', 'Finished third in MVP voting with elite scoring and defense.'),
  ('paul-george-2019-three-point-shooter', 'Paul George', 2019, '2018-19', 'three-point-shooter', 'qualifies', 'Made 292 threes at 38.6 percent on difficult volume.'),
  ('paul-george-2019-team-defender', 'Paul George', 2019, '2018-19', 'team-defender', 'qualifies', 'Steals, help, and wing coverage elevated Oklahoma City''s defense.'),
  ('blake-griffin-2014-playmaker', 'Blake Griffin', 2014, '2013-14', 'playmaker', 'qualifies', 'Expanded his passing while averaging 3.9 assists from the frontcourt.'),
  ('blake-griffin-2014-championship-number-one', 'Blake Griffin', 2014, '2013-14', 'championship-number-one', 'qualifies', 'Finished third in MVP voting as a dominant offensive centerpiece.'),
  ('blake-griffin-2014-rim-protector', 'Blake Griffin', 2014, '2013-14', 'rim-protector', 'does_not_qualify', 'Explosive athleticism produced little dependable shot deterrence or blocking.'),
  ('demarcus-cousins-2017-tough-shot-maker', 'DeMarcus Cousins', 2017, '2016-17', 'tough-shot-maker', 'qualifies', 'Converted difficult post counters, face-ups, and contested jumpers.'),
  ('demarcus-cousins-2017-ball-pounder', 'DeMarcus Cousins', 2017, '2016-17', 'ball-pounder', 'qualifies', 'High-usage post-ups and face-ups consumed substantial possession time.'),
  ('demarcus-cousins-2017-team-defender', 'DeMarcus Cousins', 2017, '2016-17', 'team-defender', 'does_not_qualify', 'Effort, transition habits, and discipline undermined consistent defensive impact.'),
  ('kyrie-irving-2016-clutch', 'Kyrie Irving', 2016, '2015-16', 'clutch', 'qualifies', 'Hit the championship-winning three over Curry in Game Seven.'),
  ('kyrie-irving-2016-three-point-shooter', 'Kyrie Irving', 2016, '2015-16', 'three-point-shooter', 'qualifies', 'Pull-up and catch shooting demanded tight coverage beyond the arc.'),
  ('kyrie-irving-2016-team-defender', 'Kyrie Irving', 2016, '2015-16', 'team-defender', 'does_not_qualify', 'Cleveland''s defense frequently had to cover his screen and effort issues.'),
  ('marc-gasol-2013-team-defender', 'Marc Gasol', 2013, '2012-13', 'team-defender', 'qualifies', 'Won Defensive Player of the Year by organizing Memphis'' elite defense.'),
  ('marc-gasol-2013-rim-protector', 'Marc Gasol', 2013, '2012-13', 'rim-protector', 'qualifies', 'Positioning and verticality deterred shots beyond his modest block total.'),
  ('marc-gasol-2013-playmaker', 'Marc Gasol', 2013, '2012-13', 'playmaker', 'qualifies', 'Elbow and post passing created cuts and open perimeter shots.'),
  ('rudy-gobert-2019-team-defender', 'Rudy Gobert', 2019, '2018-19', 'team-defender', 'qualifies', 'Won Defensive Player of the Year as Utah''s entire defensive foundation.'),
  ('rudy-gobert-2019-off-ball-scorer', 'Rudy Gobert', 2019, '2018-19', 'off-ball-scorer', 'qualifies', 'Screens, rolls, lobs, and putbacks created efficient low-touch offense.'),
  ('rudy-gobert-2019-switchable-defender', 'Rudy Gobert', 2019, '2018-19', 'switchable-defender', 'does_not_qualify', 'Utah preferred drop coverage rather than leaving him on guards.'),
  ('joakim-noah-2014-team-defender', 'Joakim Noah', 2014, '2013-14', 'team-defender', 'qualifies', 'Won Defensive Player of the Year while directing Chicago''s rotations.'),
  ('joakim-noah-2014-playmaker', 'Joakim Noah', 2014, '2013-14', 'playmaker', 'qualifies', 'Averaged 5.4 assists and initiated offense from the elbows.'),
  ('joakim-noah-2014-rim-protector', 'Joakim Noah', 2014, '2013-14', 'rim-protector', 'qualifies', 'Mobility and timing deterred drives despite moderate block totals.'),
  ('kyle-lowry-2016-playmaker', 'Kyle Lowry', 2016, '2015-16', 'playmaker', 'qualifies', 'Averaged 6.4 assists while driving Toronto''s best offense to date.'),
  ('kyle-lowry-2016-three-point-shooter', 'Kyle Lowry', 2016, '2015-16', 'three-point-shooter', 'qualifies', 'Made 212 threes and punished defenders going under screens.'),
  ('kyle-lowry-2016-championship-number-one', 'Kyle Lowry', 2016, '2015-16', 'championship-number-one', 'does_not_qualify', 'Excellent lead guard lacked the scoring ceiling of a title centerpiece.'),
  ('isaiah-thomas-2017-clutch', 'Isaiah Thomas', 2017, '2016-17', 'clutch', 'qualifies', 'Led the league in fourth-quarter scoring for the top-seeded Celtics.'),
  ('isaiah-thomas-2017-tough-shot-maker', 'Isaiah Thomas', 2017, '2016-17', 'tough-shot-maker', 'qualifies', 'Converted contested pull-ups and rim finishes despite extreme size disadvantages.'),
  ('isaiah-thomas-2017-iso-defender', 'Isaiah Thomas', 2017, '2016-17', 'iso-defender', 'does_not_qualify', 'Opponents relentlessly targeted his height and limited contest ability.'),
  ('nikola-jokic-2023-clutch', 'Nikola Jokic', 2023, '2022-23', 'clutch', 'qualifies', 'Controlled late playoff possessions with scoring, passing, and decision-making.'),
  ('nikola-jokic-2023-tough-shot-maker', 'Nikola Jokic', 2023, '2022-23', 'tough-shot-maker', 'qualifies', 'Converted awkward floaters, hooks, and late-clock jumpers throughout the postseason.');
INSERT INTO editorial_label_seed_0019 (question_id, player_name, season, season_label, trait_id, verdict, note) VALUES
  ('joel-embiid-2023-championship-number-one', 'Joel Embiid', 2023, '2022-23', 'championship-number-one', 'qualifies', 'Won MVP after leading the league with 33.1 points.'),
  ('joel-embiid-2023-rim-protector', 'Joel Embiid', 2023, '2022-23', 'rim-protector', 'qualifies', 'Size and timing deterred paint attacks beyond his block total.'),
  ('joel-embiid-2023-foul-merchant', 'Joel Embiid', 2023, '2022-23', 'foul-merchant', 'qualifies', 'Rip-throughs, flails, and contact hunting generated nearly twelve free throws.'),
  ('luka-doncic-2024-playmaker', 'Luka Doncic', 2024, '2023-24', 'playmaker', 'qualifies', 'Averaged 9.8 assists while manipulating every layer of the defense.'),
  ('luka-doncic-2024-off-ball-scorer', 'Luka Doncic', 2024, '2023-24', 'off-ball-scorer', 'does_not_qualify', 'He rarely cut, relocated, or screened when teammates controlled possessions.'),
  ('shai-gilgeous-alexander-2025-rim-pressurer', 'Shai Gilgeous-Alexander', 2025, '2024-25', 'rim-pressurer', 'qualifies', 'Deceptive drives repeatedly reached the paint and free-throw line.'),
  ('jayson-tatum-2024-championship-number-one', 'Jayson Tatum', 2024, '2023-24', 'championship-number-one', 'qualifies', 'Led Boston in scoring, rebounding, and assists during its title run.'),
  ('jayson-tatum-2024-switchable-defender', 'Jayson Tatum', 2024, '2023-24', 'switchable-defender', 'qualifies', 'Guarded wings, forwards, and centers within Boston''s switching scheme.'),
  ('jayson-tatum-2024-three-point-shooter', 'Jayson Tatum', 2024, '2023-24', 'three-point-shooter', 'qualifies', 'High-volume shooting demanded attention despite ordinary postseason accuracy.'),
  ('anthony-edwards-2024-championship-number-one', 'Anthony Edwards', 2024, '2023-24', 'championship-number-one', 'qualifies', 'Led Minnesota to the conference finals as its primary scorer.'),
  ('anthony-edwards-2024-tough-shot-maker', 'Anthony Edwards', 2024, '2023-24', 'tough-shot-maker', 'qualifies', 'Created and converted difficult pull-ups against loaded defenses.'),
  ('anthony-edwards-2024-super-three-point-shooter', 'Anthony Edwards', 2024, '2023-24', 'super-three-point-shooter', 'does_not_qualify', 'High-volume shooting mattered, but defenses did not warp around his range.'),
  ('jalen-brunson-2024-championship-number-one', 'Jalen Brunson', 2024, '2023-24', 'championship-number-one', 'qualifies', 'Finished fifth in MVP voting while carrying New York''s offense.'),
  ('jalen-brunson-2024-clutch', 'Jalen Brunson', 2024, '2023-24', 'clutch', 'qualifies', 'Repeatedly delivered late-clock scoring during an injury-ravaged playoff run.'),
  ('jalen-brunson-2024-iso-defender', 'Jalen Brunson', 2024, '2023-24', 'iso-defender', 'does_not_qualify', 'Size limitations made him a target against strong perimeter scorers.'),
  ('tyrese-haliburton-2024-playmaker', 'Tyrese Haliburton', 2024, '2023-24', 'playmaker', 'qualifies', 'Led the league with 10.9 assists and powered Indiana''s offense.'),
  ('tyrese-haliburton-2024-three-point-shooter', 'Tyrese Haliburton', 2024, '2023-24', 'three-point-shooter', 'qualifies', 'Deep pull-ups forced defenders over screens and extended pick-up points.'),
  ('tyrese-haliburton-2024-team-defender', 'Tyrese Haliburton', 2024, '2023-24', 'team-defender', 'does_not_qualify', 'Indiana''s defense gained little from his help, pressure, or physicality.'),
  ('victor-wembanyama-2025-rim-protector', 'Victor Wembanyama', 2025, '2024-25', 'rim-protector', 'qualifies', 'Averaged 3.8 blocks and radically changed paint decisions.'),
  ('victor-wembanyama-2025-three-point-shooter', 'Victor Wembanyama', 2025, '2024-25', 'three-point-shooter', 'qualifies', 'High-volume pull-ups forced centers to defend far beyond the paint.'),
  ('victor-wembanyama-2025-switchable-defender', 'Victor Wembanyama', 2025, '2024-25', 'switchable-defender', 'qualifies', 'Length and mobility let him survive guards through centers.'),
  ('ja-morant-2022-playmaker', 'Ja Morant', 2022, '2021-22', 'playmaker', 'qualifies', 'Averaged 6.7 assists while creating constant downhill advantages.'),
  ('ja-morant-2022-tough-shot-maker', 'Ja Morant', 2022, '2021-22', 'tough-shot-maker', 'qualifies', 'Finished acrobatically over length and hit difficult late-clock shots.'),
  ('ja-morant-2022-three-point-shooter', 'Ja Morant', 2022, '2021-22', 'three-point-shooter', 'does_not_qualify', 'Shot 34.4 percent as defenses still ducked under screens.');
INSERT OR IGNORE INTO trait_questions_v1
  (id, trait_id, player_name, season, season_label, player_key, prompt_override, status, editorial_priority, definition_version, created_at, updated_at)
SELECT question_id, trait_id, player_name, season, season_label, NULL, NULL, 'active', 35, 1, CAST(strftime('%s','now') AS INTEGER) * 1000, CAST(strftime('%s','now') AS INTEGER) * 1000
FROM editorial_label_seed_0019;
INSERT OR IGNORE INTO trait_editorial_v1 (question_id, verdict, note, created_at)
SELECT question_id, verdict, note, CAST(strftime('%s','now') AS INTEGER) * 1000
FROM editorial_label_seed_0019;
INSERT OR IGNORE INTO trait_question_meta_v1
  (question_id, slug, public_question, what_counts, metadata_line, homepage_eligible, share_preview, active, created_at)
SELECT s.question_id,
       s.question_id,
       CASE s.trait_id
    WHEN 'three-point-shooter' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Three-Point Shooter?'
    WHEN 'super-three-point-shooter' THEN 'Did ' || s.season || ' ' || s.player_name || ' have game-breaking three-point gravity?'
    WHEN 'iso-defender' THEN 'Was ' || s.season || ' ' || s.player_name || ' an elite Iso Defender?'
    WHEN 'team-defender' THEN 'Was ' || s.season || ' ' || s.player_name || ' an elite Team Defender?'
    WHEN 'rim-protector' THEN 'Was ' || s.season || ' ' || s.player_name || ' an elite Rim Protector?'
    WHEN 'playmaker' THEN 'Was ' || s.season || ' ' || s.player_name || ' an elite Playmaker?'
    WHEN 'clutch' THEN 'Was ' || s.season || ' ' || s.player_name || ' clutch?'
    WHEN 'rim-pressurer' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Rim Pressurer?'
    WHEN 'off-ball-scorer' THEN 'Was ' || s.season || ' ' || s.player_name || ' an elite Off-Ball Scorer?'
    WHEN 'switchable-defender' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Switchable Defender?'
    WHEN 'tough-shot-maker' THEN 'Was ' || s.season || ' ' || s.player_name || ' an elite Tough Shot Maker?'
    WHEN 'off-court-knucklehead' THEN 'Was ' || s.season || ' ' || s.player_name || ' an Off-Court Knucklehead?'
    WHEN 'ball-stopper' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Ball Stopper?'
    WHEN 'foul-merchant' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Foul Merchant?'
    WHEN 'stat-padder' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Stat Padder?'
    WHEN 'championship-number-one' THEN 'Could ' || s.season || ' ' || s.player_name || ' have been the #1 on a championship team?'
    WHEN 'ball-pounder' THEN 'Was ' || s.season || ' ' || s.player_name || ' a Ball Pounder?'
    ELSE 'Was ' || s.season || ' ' || s.player_name || ' ' || t.display_name || '?'
  END,
       t.short_definition,
       s.player_name || ' · ' || s.season_label,
       0,
       upper(CAST(s.season AS TEXT) || ' ' || s.player_name || ' · ' || t.display_name || '?'),
       1,
       CAST(strftime('%s','now') AS INTEGER) * 1000
FROM editorial_label_seed_0019 s
JOIN traits_v1 t ON t.id = s.trait_id;
DROP TABLE editorial_label_seed_0019;
