SELECT 'new questions present' label, COUNT(*) n FROM trait_questions_v1 WHERE id IN (
  'lebron-james-2011-clutch',
  'nikola-jokic-2023-team-defender',
  'rudy-gobert-2022-switchable-defender',
  'james-harden-2018-foul-merchant',
  'trae-young-2022-foul-merchant',
  'derrick-rose-2011-championship-number-one',
  'russell-westbrook-2021-stat-padder',
  'kobe-bryant-2006-clutch',
  'shaquille-o-neal-2000-clutch',
  'reggie-miller-1995-clutch',
  'robert-horry-2002-clutch',
  'demar-derozan-2022-clutch',
  'jimmy-butler-2023-tough-shot-maker',
  'ja-morant-2023-off-court-knucklehead',
  'kyrie-irving-2022-off-court-knucklehead',
  'draymond-green-2023-off-court-knucklehead',
  'dennis-rodman-1996-off-court-knucklehead',
  'wilt-chamberlain-1967-stat-padder',
  'vince-carter-2000-championship-number-one',
  'dwyane-wade-2006-championship-number-one',
  'julius-randle-2021-ball-stopper',
  'chris-paul-2021-clutch',
  'joel-embiid-2022-rim-protector',
  'zion-williamson-2023-rim-pressurer'
);

SELECT 'new meta homepage-eligible' label, COUNT(*) n FROM trait_question_meta_v1 WHERE homepage_eligible = 1 AND active = 1 AND question_id IN (
  'lebron-james-2011-clutch',
  'nikola-jokic-2023-team-defender',
  'rudy-gobert-2022-switchable-defender',
  'james-harden-2018-foul-merchant',
  'trae-young-2022-foul-merchant',
  'derrick-rose-2011-championship-number-one',
  'russell-westbrook-2021-stat-padder',
  'kobe-bryant-2006-clutch',
  'shaquille-o-neal-2000-clutch',
  'reggie-miller-1995-clutch',
  'robert-horry-2002-clutch',
  'demar-derozan-2022-clutch',
  'jimmy-butler-2023-tough-shot-maker',
  'ja-morant-2023-off-court-knucklehead',
  'kyrie-irving-2022-off-court-knucklehead',
  'draymond-green-2023-off-court-knucklehead',
  'dennis-rodman-1996-off-court-knucklehead',
  'wilt-chamberlain-1967-stat-padder',
  'vince-carter-2000-championship-number-one',
  'dwyane-wade-2006-championship-number-one',
  'julius-randle-2021-ball-stopper',
  'chris-paul-2021-clutch',
  'joel-embiid-2022-rim-protector',
  'zion-williamson-2023-rim-pressurer'
);

SELECT 'homepage pool total' label, COUNT(*) n FROM trait_question_meta_v1 m JOIN trait_questions_v1 q ON q.id = m.question_id WHERE m.homepage_eligible = 1 AND m.active = 1 AND q.status = 'active';

SELECT q.id, m.public_question FROM trait_questions_v1 q JOIN trait_question_meta_v1 m ON m.question_id = q.id WHERE q.id IN (
  'lebron-james-2011-clutch',
  'nikola-jokic-2023-team-defender',
  'rudy-gobert-2022-switchable-defender',
  'james-harden-2018-foul-merchant',
  'trae-young-2022-foul-merchant',
  'derrick-rose-2011-championship-number-one',
  'russell-westbrook-2021-stat-padder',
  'kobe-bryant-2006-clutch',
  'shaquille-o-neal-2000-clutch',
  'reggie-miller-1995-clutch',
  'robert-horry-2002-clutch',
  'demar-derozan-2022-clutch',
  'jimmy-butler-2023-tough-shot-maker',
  'ja-morant-2023-off-court-knucklehead',
  'kyrie-irving-2022-off-court-knucklehead',
  'draymond-green-2023-off-court-knucklehead',
  'dennis-rodman-1996-off-court-knucklehead',
  'wilt-chamberlain-1967-stat-padder',
  'vince-carter-2000-championship-number-one',
  'dwyane-wade-2006-championship-number-one',
  'julius-randle-2021-ball-stopper',
  'chris-paul-2021-clutch',
  'joel-embiid-2022-rim-protector',
  'zion-williamson-2023-rim-pressurer'
) ORDER BY q.editorial_priority DESC, q.id;
